### ISSUE TITLE
Application location is untrusted. Copy file to a local drive, and try again.

### ISSUE THREAD

**Issue by hieblmedia** [MinersWin/TGF-Tuning-Pack-4.0#1]
Hallo,
wollte das Tool gerade in einem VM Container ausführen zum testen um ggf. die Hintergrundprozesse zu minimieren.
Es erscheint aber folgende Fehlermeldung: "Application location is untrusted. Copy file to a local drive, and try again."
Siehe https://prnt.sc/qlprit

**Comment by MinersWin** [comment]
Das Problem ist, dass das Tuning Pack das Internet Explorer Modul aus dem .Net-Framework nutzt, um die neuste Version abzurufen. Dies ist unter Windows 10 allerdings nicht mehr so einfach Möglich, deshalb muss der Internet Explorer vor dem ersten Ausführen einmalig gestartet und danach Wieder geschlossen werden.
Mit dem neuen Update, sollte es wieder Funktionieren. Außerdem wurden mit dem neuen Update **sehr Viele!** neue Funktionen eingefügt, welche unter anderem auch die Leistung sehr steigern sollten. Bitte tu mir den gefallen und lese dir durch, was du machst. Was du nicht verstehst solltest du erst gar nicht Auswählen.
MfG MinersWin
