### ISSUE TITLE
xcross check 

### ISSUE THREAD

**Issue by goldjunge91** [MinersWin/TGF-Tuning-Pack-4.0#6]
Hi,
es wäre cool das nach dem Starten der Software diese kein preset lädt sondern erst mal anzeigt was man selber geändert vorher schon. eventuell in verschiedenen farben.

**Comment by goldjunge91** [comment]
dann wäre noch schon zu sehen was im Hintergrund wie geändert wird um sachen eventuell zurück zu setzen auf default das gibt es nämlich bis auf ein backup einspielen auch nicht

**Comment by MinersWin** [comment]
Hey,
Ja das ist eine Gute Idee, allerdings ist das mit einer Menge Arbeit verbunden.
Das komplette Pack müsste hierfür umgeschrieben werden weil erstmal Checks eingebaut werden müssten, um herauszufinden wie die aktuellen Einstellungen sind, sowie für jeden Tweak einmal den entsprechenden "Anti-Tweak" einzubauen.

Vielleicht kommt das noch, allerdings fehlt mir hierfür im Moment einfach die Zeit :/

**Comment by MinersWin** [comment]
CLOSED
