### ISSUE TITLE
Wird von Windows Defender geblockt

### ISSUE THREAD

**Issue by morphi83** [MinersWin/TGF-Tuning-Pack-4.0#7]
Folgendes zeigt WIndows Defender an nachdem man die Tuningpack.exe ausführt. 

Trojan:Script/Woreflint.A!cl

file: C:\Windows\SysWOW64\TuningPack.zip

Gruss Manuel

**Comment by morphi83** [comment]
sowohl bei 4.2 als auch 4.3alpha

**Comment by elaaar** [comment]
Trojan:Script/Woreflint.A!c

Same windoof 10

**Comment by WarZoneTeam** [comment]
@elaaar @morphi83
False/Positive :)
das Problem ist, soweit Win-Defender merkt das irgendwas verändert wird, wird er Nerven.
Das Tool ist 1000 % Clean
Ihr Könnt den Defender mal kurz abschalten, das er keine Prozesse blockiert während Ihr das Tool nutzt, was zum Schaden führen kann!

Long story short : Defender 10 min offline legen! Und das Tool mit Admin Rechten starten nur dann wird das Ergebnis perfekt sein, PC neu starten und Ihr habt ein Perfektes Windows 10

**Comment by MinersWin** [comment]
Tiefgreifende Systemänderungen werden häufig von Viren gemacht und sind ohne teure Zertifikate und Audits deswegen von Virenscannern als Bedrohung eingestuft. Zum Beispiel ändern wir etwas an der Hosts Datei um zum Beispiel die Microsoft Telemetrie Server zu blockieren. Dies wird allerdings auch häufig von Viren gemacht um z.B. einfachere Man in the Middle Attacken oder ähnliches auszuführen.
Von daher das Tool ist Clean, allerdings nicht in den Augen der AV Hersteller. Ich bin nicht bereit oder überhaupt in der Lage mir teure Zertifikate in hohen dreistelligen Beträgen zu kaufen und die AV Hersteller um Audits anzufragen, welche nach jeden Update sowieso wieder erneuert werden müssen. Hierfür fehlen mir Leider einfach die Zeit und Mittel.
Am besten den Virenschutz vor dem Ausführen deaktivieren dann sollte dies kein Problem sein.

**Comment by MinersWin** [comment]
CLOSED
